services:
  db:
    image: mariadb:11.4
    ports:
      - 3406:3306
    restart: always
    volumes:
      - mariadb_origin:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=origin
      - MYSQL_USER=origin
      - MYSQL_PASSWORD=origin
      - MYSQL_ROOT_PASSWORD=origin

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8030:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=origin
      - PMA_PASSWORD=origin

  server:
    image: origin:latest
    ports:
      - 8010:8010
    depends_on:
      - db

volumes:
  mariadb_origin:

