export enum MutationTypes {
    SET_SSID = 'SET_SSID',
    SET_LAST_ERROR = 'SET_LAST_ERROR',
    INVENTORY_UPDATE = 'INVENTORY_UPDATE',
    INVENTORY_CLOSE = 'INVENTORY_CLOSE',
    INVENTORIES_CLEAR = 'INVENTORIES_CLEAR',
    SET_HAND = 'SET_HAND',
}