const url0 = require("../../assets/img/clock0.png")
const url1 = require("../../assets/img/clock1.png")
const url2 = require("../../assets/img/clock2.png")
const url3 = require("../../assets/img/clock3.png")
const url4 = require("../../assets/img/clock4.png")
const url5 = require("../../assets/img/clock5.png")
const url6 = require("../../assets/img/clock6.png")
const url7 = require("../../assets/img/clock7.png")
const url8 = require("../../assets/img/clock8.png")
const url9 = require("../../assets/img/clock9.png")
const url10 = require("../../assets/img/clock10.png")
const url11 = require("../../assets/img/clock11.png")
const url12 = require("../../assets/img/clock12.png")
const url13 = require("../../assets/img/clock13.png")
const url14 = require("../../assets/img/clock14.png")
const url15 = require("../../assets/img/clock15.png")
const url16 = require("../../assets/img/clock16.png")
const url17 = require("../../assets/img/clock17.png")
const url18 = require("../../assets/img/clock18.png")
const url19 = require("../../assets/img/clock19.png")
const url20 = require("../../assets/img/clock20.png")
const url21 = require("../../assets/img/clock21.png")

export function imagePreload(url: any) {
    const img = new Image()
    img.src = url
}

export function preloadClock() {
    imagePreload(url0)
    imagePreload(url1)
    imagePreload(url2)
    imagePreload(url3)
    imagePreload(url4)
    imagePreload(url5)
    imagePreload(url6)
    imagePreload(url7)
    imagePreload(url8)
    imagePreload(url9)
    imagePreload(url10)
    imagePreload(url11)
    imagePreload(url12)
    imagePreload(url13)
    imagePreload(url14)
    imagePreload(url15)
    imagePreload(url16)
    imagePreload(url17)
    imagePreload(url18)
    imagePreload(url19)
    imagePreload(url20)
    imagePreload(url21)
}
